nick:     schrader
channel:  "#en.wikipedia"
server:   browne.wikimedia.org
port:     6667
user:     schrader
site:     "http://en.wikipedia.org"
api:      "http://en.wikipedia.org/w/api.php"
language: en
